codecov:
  notify:
    wait_for_ci: false
  require_ci_to_pass: false
# coverage:
#   range: 90..98
#   status:
#     project:
#       default:
#         # Temporarily allow a greater project coverage threshold; see #2757
#         threshold: 0.9%
#         removed_code_behavior: adjust_base
#     patch:
#       default:
#         threshold: 0.5%
#         removed_code_behavior: adjust_base
