name: WiPPLPy
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python
  - jupyter
  - numpy < 2
  - scipy
  - matplotlib
  - mdsplus
  - tqdm
  - configobj
  - pyyaml
  - sphinx
  - pip
  - pip:
    - nox
    - pytest
    - pytest-cov
