name: CI

on:
  push:
    branches:
    - main
    - stable
    - v*.*.*
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Tests, Python 3.12, Ubuntu
          os: ubuntu-latest
          python: '3.12'
          nox_session: tests-3.12

        - name: Tests, Python 3.11, macOS
          os: macos-latest
          python: '3.11'
          nox_session: tests-3.11

        - name: Tests, Python 3.10, Windows
          os: windows-latest
          python: '3.10'
          nox_session: tests-3.10

        - name: Documentation, Python 3.12, Ubuntu
          os: ubuntu-latest
          python: '3.12'
          nox_session: docs

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install Python dependencies
        run: python -m pip install --progress-bar off --upgrade nox uv

      - name: Run tests
        run: nox -s ${{ matrix.nox_session }}

      - name: Upload coverage to codecov
        if: ${{ contains(matrix.nox_session,'cov') }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
